runtime: php
env: flex
runtime_config:
    document_root: .
env_variables:
    APP_LOG: errorlog
    GOOGLE_STORAGE_BUCKET: "api-project-266311.appspot.com"
    MYSQL_USER: ""
    MYSQL_PASSWORD: ""
    MYSQL_DSN: "mysql:dbname=testdb;unix_socket=/cloudsql/api-project-266311:europe-west3:esp-lp-mysql"
beta_settings:
    cloud_sql_instances: "api-project-266311:europe-west3:esp-lp-mysql"
